# -*- coding: utf-8 -*-
"""DMX1_RB.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uevOnuDaGP4V0bMrrQ0gGX-Cv_SKOprf
"""

pip install yahoofinancials

pip install yfinance

import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt 
import datetime
from datetime import date, timedelta
import yfinance as yf
from yahoofinancials import YahooFinancials as yfn

today = date.today()
start= datetime.datetime(2021,1,1,0,0)
end=datetime.datetime(today.year, today.month, today.day)
google_data= yf.download('GOOGL', start, end, progress=False)
print(google_data)

google_data.any()

google_data.isnull().any()

google_data.info()

google_data.describe()

plt.title("Stock Market Changes over 2 years")
google_data['Open'].plot(label="Open Price", figsize=(15,7))
google_data['Close'].plot(label="Close Price")
plt.ylabel('Price in $')
plt.xlabel('Months')
plt.legend()
plt.show()

plt.title("Moving Average")
google_data['Moving Average']=google_data['Open'].rolling(30).mean()
google_data['Moving Average'].plot(label="Moving average",figsize=(15,7))
google_data['Open'].plot(label="Open Price",figsize=(15,7))
# apple_data['Close'].plot(Label="Close Price")
plt.legend()

google_data['Moving Average'].plot(label="Google", figsize=(15,7))

google_data["Date"]= google_data.index
google_data = google_data[["Date", "Open", "High", "Low", 
             "Close", "Adj Close", "Volume"]]
google_data["Date"]

import plotly.express as px
figure = px.bar(google_data, x="Date", y="Volume")
figure.show()

google_data['Daily Return'] = google_data['Close'] - google_data['Open']

google_data['Daily Return']

google_data['Daily Return'].mean()

google_data["Trends"] = np.where(google_data["Daily Return"] >=0, "Positive" ,"Negative")
google_data

google_data.Trends.value_counts().plot(kind="pie", labels=['positive', 'negative'])
plt.axis('equal')
plt.title('Trend Frequency')

today = date.today()
start = datetime.datetime(2021,1,1,0,0)
end = datetime.datetime(today.year, today.month, today.day)
amazon_data = yf.download('AMZN', start , end,progress=False)
#apple_data = yf.download('APPL', start , end,progress=False)
microsoft_data = yf.download('MSFT', start , end,progress=False)

plt.title("Stock Price Changes Over Time")
amazon_data['Open'].plot(label="Amazon",figsize=(15,7))
microsoft_data['Open'].plot(label="MicroSoft")
google_data['Open'].plot(label="Google")
#apple_data['Open'].plot(label="Apple")
plt.ylabel('Open')
plt.xlabel('Days')
plt.legend()
plt.show()

plt.title("Stock Price Changes Over Time")
amazon_data['Volume'].plot(label="Amazon",figsize=(15,7))
microsoft_data['Volume'].plot(label="MicroSoft")
google_data['Volume'].plot(label="Google")
#apple_data['Volume'].plot(label="Apple")
plt.ylabel('Volume')
plt.xlabel('Days')
plt.legend()
plt.show()

google_data['Daily Return'] = google_data['Close']-google_data['Open']
microsoft_data['Daily Return'] = microsoft_data['Close']-microsoft_data['Open']
amazon_data['Daily Return'] = amazon_data['Close']-amazon_data['Open']

correlation=pd.concat([google_data['Daily Return'],microsoft_data['Daily Return'],amazon_data['Daily Return']],axis=1)
correlation.columns={"Google Return","Microsoft Return","Amazon Return"}
correlation

correlation.corr()

import seaborn as sns
cor=correlation.corr()
plt.figure(figsize=(15,7))
sns.heatmap(data=cor, annot=True)

from pandas.plotting import scatter_matrix as scx
scx(correlation, figsize=(15,7))

